micronaut:
  application:
    name: concordv1
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:jodhansingh}"'

team:
  name: 'Michigan Wolverines'
  color: 'Maize and Blue'
  coach:
    - 'Jim Harbaugh'
    - 'McDonald'

endpoints:
  info:
    enabled: true
    sensitive: false
